---

clone:
  git:
    image: plugins/git
    recursive: true
    submodule_override:
      plugins: https://github.com/getpelican/pelican-plugins.git
      themes: https://github.com/agrrh/pelican-themes.git
    volumes:
      - /tmp/drone_src:/drone/src

pipeline:
  publish:
    image: plugins/docker
    repo: agrrh/website
    tags: [ "latest" ]
    secrets: [ docker_username, docker_password ]
    dockerfile: Dockerfile
    when:
      branch: master
      event: push
