---

clone:
  git:
    image: plugins/git
    volumes:
      - /tmp/drone_src:/drone/src

pipeline:
  publish:
    image: plugins/docker
    repo: agrrh/website
    tags:
      - latest
    secrets:
      - docker_username
      - docker_password
    dockerfile: Dockerfile
    purge: false
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/drone_src:/drone/src
    when:
      branch: master
      event: push
