---

clone:
  git:
    image: plugins/git
    recursive: true
    submodule_override:
      plugins: https://github.com/getpelican/pelican-plugins.git
      themes: https://github.com/agrrh/pelican-themes.git
    volumes:
      - /tmp/drone_src:/drone/src

pipeline:
  publish:
    image: docker:18-ce
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker build . -t agrrh/website
      - docker push agrrh/website
    when:
      event: [push]
