---

pipeline:
  build-docker:
    image: docker:17.12.1-ce
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker build . -t drone-example:${DRONE_COMMIT_SHA}
    when:
      event: [push]

