---

clone:
  git:
    image: plugins/git
    recursive: true
    submodule_override:
      plugins: https://github.com/getpelican/pelican-plugins.git
      themes: https://github.com/agrrh/pelican-themes.git
    volumes:
      - /drone/src:/tmp/drone_src

pipeline:
  build-docker:
    image: docker:17.12.1-ce
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - date
      - docker build . -t drone-example:${DRONE_COMMIT_SHA}
    when:
      event: [push]
