---

clone:
  git:
    image: plugins/git
    recursive: true
    submodule_override:
      plugins: https://github.com/getpelican/pelican-plugins.git
      themes: https://github.com/agrrh/pelican-themes.git
    volumes:
      - /tmp/drone_src:/drone/src

pipeline:
  publish:
    image: docker:18
    secrets: [ docker_username, docker_password ]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/drone_src:/drone/src
    commands:
      - docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
      - docker build . -t agrrh/website
      - docker push agrrh/website
    when:
      event: [push]
